name: mildrok
favicon: null
layout_spectrum: 0.58047
typography_spectrum: 0.55687
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.3248247669544071
  lightness: 0.4622719017788768
  saturation: 0.059181917225942016
  rhythmicContrast: 0.407791679026559
purpose: []
